config/routes.rb
Rails.application.routes.draw do
  resources :distributions
  resources :datasets
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dataset.rb
class Dataset < ApplicationRecord
end

app/models/distribution.rb
class Distribution < ApplicationRecord
  belongs_to :dataset
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  before_action :set_dataset, only: [:show, :edit, :update, :destroy]

  # GET /datasets
  # GET /datasets.json
  def index
    @datasets = Dataset.all
  end

  # GET /datasets/1
  # GET /datasets/1.json
  def show
    @distribution = Distribution.where(dataset_id: params[:id]).all
  end

  # GET /datasets/new
  def new
    @dataset = Dataset.new
  end

  # GET /datasets/1/edit
  def edit
  end

  # POST /datasets
  # POST /datasets.json
  def create
    @dataset = Dataset.new(dataset_params)

    respond_to do |format|
      if @dataset.save
        format.html { redirect_to @dataset, notice: 'Dataset was successfully created.' }
        format.json { render :show, status: :created, location: @dataset }
      else
        format.html { render :new }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datasets/1
  # PATCH/PUT /datasets/1.json
  def update
    respond_to do |format|
      if @dataset.update(dataset_params)
        format.html { redirect_to @dataset, notice: 'Dataset was successfully updated.' }
        format.json { render :show, status: :ok, location: @dataset }
      else
        format.html { render :edit }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datasets/1
  # DELETE /datasets/1.json
  def destroy
    @dataset.destroy
    respond_to do |format|
      format.html { redirect_to datasets_url, notice: 'Dataset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dataset
      @dataset = Dataset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dataset_params
      params.require(:dataset).permit(:title, :name_creator, :human_identifier, :organization_identifier, :accessrights, :name_contactpoint, :phone_contactpoint, :phone_creator, :language, :name_publisher, :phone_publisher, :description, :theme, :category, :keyword, :landingpage, :rights, :accrualperiodicity, :spatial, :spatialresolutionInMeters, :temporal, :temporalresolution, :version, :versiondescription)
    end
end

app/controllers/distributions_controller.rb
class DistributionsController < ApplicationController
  before_action :set_distribution, only: [:show, :edit, :update, :destroy]

  # GET /distributions
  # GET /distributions.json
  def index
    @distributions = Distribution.all
  end

  # GET /distributions/1
  # GET /distributions/1.json
  def show
  end

  # GET /distributions/new
  def new
    @distribution = Distribution.new
  end

  # GET /distributions/1/edit
  def edit
  end

  # POST /distributions
  # POST /distributions.json
  def create
    @distribution = Distribution.new(distribution_params)

    respond_to do |format|
      if @distribution.save
        format.html { redirect_to @distribution, notice: 'Distribution was successfully created.' }
        format.json { render :show, status: :created, location: @distribution }
      else
        format.html { render :new }
        format.json { render json: @distribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /distributions/1
  # PATCH/PUT /distributions/1.json
  def update
    respond_to do |format|
      if @distribution.update(distribution_params)
        format.html { redirect_to @distribution, notice: 'Distribution was successfully updated.' }
        format.json { render :show, status: :ok, location: @distribution }
      else
        format.html { render :edit }
        format.json { render json: @distribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distributions/1
  # DELETE /distributions/1.json
  def destroy
    @distribution.destroy
    respond_to do |format|
      format.html { redirect_to distributions_url, notice: 'Distribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_distribution
      @distribution = Distribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def distribution_params
      params.require(:distribution).permit(:dataset_id, :title, :mediatype, :accessservice)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/helpers/distributions_helper.rb
module DistributionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/datasets/_form.html.erb
<%= form_for(@dataset, html: { role: "form" }) do |f| %>
  <% if @dataset.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@dataset.errors.count, "error") %> prohibited this dataset from being saved:</h4>

      <ul>
      <% @dataset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :name_of_creator %>
  <%= f.text_field :name_creator, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :phone_of_creator %>
  <%= f.text_field :phone_creator, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :human_identifier %>
  <%= f.text_field :human_identifier, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :organization_identifier %>
  <%= f.text_field :organization_identifier, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :accessrights %>
  <%= f.text_field :accessrights, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :name_of_contactpoint %>
  <%= f.text_field :name_contactpoint, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :phone_of_contactpoint %>
  <%= f.text_field :phone_contactpoint, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :name_of_publisher %>
  <%= f.text_field :name_publisher, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :phone_of_publisher %>
  <%= f.text_field :phone_publisher, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :language %>
  <%= f.text_field :language, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, cols: "50", rows: "10", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :catagory %>
  <%= f.text_field :theme, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :type %>
  <%= f.text_field :category, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :keyword %>
  <%= f.text_area :keyword, cols: "50", rows: "5", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :landingpage %>
  <%= f.text_field :landingpage, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :rights %>
  <%= f.text_field :rights, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :accrualperiodicity %>
  <%= f.text_field :accrualperiodicity, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :spatial %>
  <%= f.text_field :spatial, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :spatialresolutionInMeters %>
  <%= f.text_field :spatialresolutionInMeters, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :temporal %>
  <%= f.text_field :temporal, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :temporalresolution %>
  <%= f.text_field :temporalresolution, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :version %>
  <%= f.text_field :version, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :versiondescription %>
  <%= f.text_area :versiondescription, cols: "50", rows: "10", class: "form-control" %>
</div>

<%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>



  

app/views/datasets/edit.html.erb
<h1>Editing Dataset</h1>

<%= render 'form', dataset: @dataset %>

<%= link_to 'Show', @dataset %> |
<%= link_to 'Back', datasets_path %>

app/views/datasets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Datasets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Creator</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= content_tag_for(:tr, @datasets) do |dataset| %>
        <td><%=link_to dataset.title, dataset_path(dataset) %></td>
        <td><%= dataset.name_creator %></td>
        <td>
          <%= link_to 'Edit', edit_dataset_path(dataset) %> |
          <%= link_to 'Destroy', dataset, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dataset', new_dataset_path %>

app/views/datasets/new.html.erb
<h1>New Dataset</h1>

<%= render 'form', dataset: @dataset %>

<%= link_to 'Back', datasets_path %>

app/views/datasets/show.html.erb
<p id="notice"><%= notice %></p>

<div align = "left">
<article typeof="dcat:Dataset">
  <dl>
    <dt>Title</dt> 
      <dd property="dc:title"><%= @dataset.title %></dd>
    <dt>Identifiers</dt>
       <dd property="dc:identifier"><%= @dataset.human_identifier %></dd>
       <dd property="dc:identifier"><%= @dataset.organization_identifier %></dd>
     <dt>AccessRights</dt>
       <dd property="dc:AccessRights"><%= @dataset.accessrights %></dd>
     <dt>ContactPoint</dt>
       <dd property="dc:contactPoint">name: <%= @dataset.name_contactpoint %>, phone: <%= @dataset.phone_contactpoint %></dd>  
    <dt>Creator</dt>
      <dd property="dc:creator">name: <%= @dataset.name_creator %>, phone: <%= @dataset.phone_creator %></dd> 
    <dt>Issuesd</dt>
      <dd property="dc:issued"> <%= @dataset.created_at %></dd>
    <dt>Modified</dt>
      <dd property="dc:modified"> <%= @dataset.updated_at %></dd>
    <dt>Language</dt>
       <dd property="dc:language"><%= @dataset.language %></dd>
     <dt>Publisher</dt>
      <dd property="dc:publisher">name: <%= @dataset.name_publisher %>, phone: <%= @dataset.phone_creator %></dd>
     <dt>Description</dt>
      <dd property="dc:description"><%= @dataset.description %></dd>
    <dt>Category</dt>
      <dd rel="dc:theme"><%= @dataset.theme %></dd>
    <dt>Type</dt>
      <dd rel="dc:type"><%= @dataset.category %></dd>
    <dt>Keyword</dt>
      <dd rel="dc:keyword"><%= @dataset.keyword %></dd>
    <dt>LandingPage</dt>
      <dd rel="dc:landingPage"><%= @dataset.landingpage %></dd>
    <dt>Rights</dt>
      <dd rel="dc:rights"><%= @dataset.rights %></dd>
    <dt>AccrualPeriodicity</dt>
      <dd rel="dc:AccrualPeriodicity"><%= @dataset.accrualperiodicity %></dd>
    <dt>Spatial</dt>
      <dd rel="dc:spatial"><%= @dataset.spatial %></dd>
    <dt>SpatialResolutionInMeters</dt>
      <dd rel="dc:spatialResolutionInMeters"><%= @dataset.spatialresolutionInMeters %></dd>
    <dt>Temporal</dt>
      <dd rel="dc:temporal"><%= @dataset.temporal %></dd> 
    <dt>TemporalResolution</dt>
      <dd rel="dc:temporalResolution"><%= @dataset.temporalresolution %></dd>
    <dt>Version</dt>
      <dd rel="dc:version"><%= @dataset.version %></dd> 
    <dt>VersionDescription</dt>
      <dd rel="dc:versionDescription"><%= @dataset.versiondescription %></dd>
    <% if @distribution.length != 0 %>   
      <dt class="field-label">Downloads:</dt>
      <% @distribution.each do |distribution| %>
        <dd>
          <ul>
            <li>
              <a rel="dcat:distribution" href="../distributions/<%= distribution.id %> "><span property="dcat:mediaType" content="<%= distribution.mediatype %>" ><%= distribution.title%></span></a>
            </li><%= distribution.mediatype %>
          </ul>
        </dd>
      <% end %>
    <% end %>
  </dl>

</article>    
  


<%= link_to 'Edit', edit_dataset_path(@dataset) %> |
<%= link_to 'Add Distribution', new_distribution_path(@dataset) %> |
<%= link_to 'Back', datasets_path %>

app/views/distributions/_form.html.erb
<%= form_with(model: distribution, local: true) do |form| %>
  <% if distribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(distribution.errors.count, "error") %> prohibited this distribution from being saved:</h2>

      <ul>
      <% distribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :dataset_id %>
    <%= form.select :dataset_id, Dataset.all.collect {|x| [x.title, x.id]}, {} %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :mediatype %>
    <%= form.text_field :mediatype %>
  </div>

  <div class="field">
    <%= form.label :accessservice %>
    <%= form.text_field :accessservice %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/distributions/edit.html.erb
<h1>Editing Distribution</h1>

<%= render 'form', distribution: @distribution %>

<%= link_to 'Show', @distribution %> |
<%= link_to 'Back', distributions_path %>

app/views/distributions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Distributions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Mediatype</th>
      <th>Accessservice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @distributions.each do |distribution| %>
      <tr>
        <td><%= distribution.title %></td>
        <td><%= distribution.mediatype %></td>
        <td><%= distribution.accessservice %></td>
        <td><%= link_to 'Show', distribution %></td>
        <td><%= link_to 'Edit', edit_distribution_path(distribution) %></td>
        <td><%= link_to 'Destroy', distribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Distribution', new_distribution_path %>

app/views/distributions/new.html.erb
<h1>New Distribution</h1>

<%= render 'form', distribution: @distribution %>

<%= link_to 'Back', distributions_path %>

app/views/distributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @distribution.title %>
</p>

<p>
  <strong>Mediatype:</strong>
  <%= @distribution.mediatype %>
</p>

<p>
  <strong>Accessservice:</strong>
  <%= @distribution.accessservice %>
</p>

<%= link_to 'Edit', edit_distribution_path(@distribution) %> |
<%= link_to 'Back', distributions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DELAB 저장소</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="google-site-verification" content="XaabjsGIDYhZKBErGbBE-yjZnaWLoFMpo7Mfag1ix5A" />  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>DELAB 연구용 데이터셋 저장소</h1>
<p>Dataset repository for research purpose</p>
<a href="/datasets">Datasets</a>